version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/app
    environment:
      KUBECONFIG: /home/circleci/config
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: Set Environment
          command: |
            echo 'export DOCKER_IMAGE=wilsontanwm/gotest' >> $BASH_ENV

      - run:
          name: Install Kubectl
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo touch /etc/apt/sources.list.d/kubernetes.list
            echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl
      
      - run:
          name: Docker Login and Set Kubectl Credential
          command: |
            echo ${GKE_CREDENTIAL_KEY} | base64 --decode --ignore-garbage > ${KUBECONFIG}
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      
      - run:
          name: Run Build and Test
          command: |
            go build .
            cd test && go test -v

      # - run:
      #     name: Docker Build and Push to Container Registry
      #     command: |
      #       docker build -t ${DOCKER_IMAGE}:${CIRCLE_SHA1} -t ${DOCKER_IMAGE}:latest . -f Dockerfile
      #       docker push ${DOCKER_IMAGE}:${CIRCLE_SHA1}
      #       docker push ${DOCKER_IMAGE}:latest

      # - deploy:
      #     name: Deploy to Kubernetes
      #     command: |
      #       kubectl apply -f kubernetes/deployment.yaml
      #       kubectl set image deployment/hello-world hello-world=${DOCKER_IMAGE}:${CIRCLE_SHA1} --namespace=${ENVIRONMENT}

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master