version: 2.1
orbs:
  gcp-gke: circle/gcp-gke@0.1.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Run Build and Test
          command: |
            go build .
            cd test && go test -v

  dockerize:
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
        name: Set Environment
        command: |
          echo 'export DOCKER_IMAGE=wilsontanwm/gotest' >> $BASH_ENV

      - run:
        name: Docker Login
        command: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - deploy:
        name: Docker Build and Push to Container Registry
        command: |
          docker build -t ${DOCKER_IMAGE}:${CIRCLE_SHA1} -t ${DOCKER_IMAGE}:latest . -f Dockerfile
          docker push ${DOCKER_IMAGE}:${CIRCLE_SHA1}
          docker push ${DOCKER_IMAGE}:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      
      - dockerize:
          requires:
            -build
          filters:
            branches:
              only:
                - master