apiVersion: v1
kind: Namespace
metadata:
  name: 'sandbox'
  labels:
    name: 'sandbox'
---
apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: hello-world
  labels:
    app: hello-world
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010
      protocol: TCP
      name: hello-world
  type: NodePort
  selector:
    app: hello-world
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: sandbox
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: wilsontanwm/gotest:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: sandbox
  name: hello-world-routing
  annotations:
    kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /    
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: hello-world
            servicePort: 80